#!/usr/bin/env python3
"""Exact checks for the issue #3 boundary chart and repair controls."""
from __future__ import annotations

import sympy as sp


def check_open_plane_and_boundary() -> None:
    u, s, e, v = sp.symbols("u s e v", nonzero=True)
    w = u * s
    z = 1 - u * s
    e_open = s * (1 - u * s)
    v_open = u * s**3 - s**2

    assert sp.expand(w * z - u * e_open) == 0
    assert sp.expand(w * e_open + u * v_open) == 0
    assert sp.expand(e_open**2 + v_open * z) == 0

    jac = sp.factor(
        sp.diff(u, u) * sp.diff(v_open, s)
        - sp.diff(u, s) * sp.diff(v_open, u)
    )
    assert jac == s * (3 * u * s - 2)

    # Boundary E has generic coordinates (e,v), with z=-e^2/v,
    # u=-e/v-e^3/v^2 and s=-v/e.
    u_ev = -e / v - e**3 / v**2
    s_ev = -v / e
    boundary_jac = sp.factor(
        sp.diff(u_ev, e) * sp.diff(s_ev, v)
        - sp.diff(u_ev, v) * sp.diff(s_ev, e)
    )
    assert boundary_jac == e / v**2


def check_affine_coordinate_repairs() -> None:
    u, s, alpha, k = sp.symbols("u s alpha k")
    r = u + alpha * s
    h0, h1, h2, h3, h4 = sp.symbols("h0:5")
    H = h0 + h1 * r + h2 * r**2 + h3 * r**3 + h4 * r**4
    Q = k * s + H
    P = r
    jac = sp.factor(
        sp.diff(P, u) * sp.diff(Q, s)
        - sp.diff(P, s) * sp.diff(Q, u)
    )
    assert jac == k

    # Conversely, solve the constant-coefficient transport equation on all
    # monomials of total degree <=4.  Its solution space has exactly the basis
    # 1, s (inhomogeneous direction), r, r^2, r^3, r^4.
    monomials = [u**i * s**j for i in range(5) for j in range(5 - i)]
    cs = sp.symbols(f"c0:{len(monomials)}")
    q = sp.expand(sum(c * m for c, m in zip(cs, monomials)))
    residual = sp.Poly(sp.diff(q, s) - alpha * sp.diff(q, u) - k, u, s)
    equations = [sp.Eq(coef, 0) for coef in residual.coeffs()]
    solution = sp.linsolve([eq.lhs for eq in equations], cs)
    assert solution is not sp.EmptySet

    # Direct containment check: every displayed solution has constant Jacobian,
    # and the homogeneous kernel is generated by polynomials in r.
    for power in range(5):
        assert sp.expand((sp.diff(r**power, s) - alpha * sp.diff(r**power, u))) == 0
    assert sp.expand(sp.diff(s, s) - alpha * sp.diff(s, u) - 1) == 0

    # With the first target coordinate fixed as u, the issue #3 map cannot be
    # repaired without deleting every nonlinear s-term.
    q_issue3 = u * s**3 - s**2
    assert sp.factor(sp.diff(q_issue3, s)) == s * (3 * u * s - 2)


def main() -> int:
    check_open_plane_and_boundary()
    check_affine_coordinate_repairs()
    print("countermodel boundary checks: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
