#!/usr/bin/env python3
"""Render maintained Markdown views from machine-readable repository data."""
from __future__ import annotations

import argparse
import json
import os
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]


def load_json(path: str) -> dict[str, Any]:
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def cell(value: Any) -> str:
    if value is None or value == "":
        return "—"
    text = str(value).replace("\n", " ").replace("|", "\\|")
    return " ".join(text.split())


def code(value: str) -> str:
    return f"`{value}`"


def relative_link(output_path: str, target: str, label: str | None = None) -> str:
    start = (ROOT / output_path).parent
    rel = os.path.relpath(ROOT / target, start=start).replace(os.sep, "/")
    return f"[{label or Path(target).name}]({rel})"


def render_claim_ledger(claims: dict[str, Any]) -> str:
    items = claims["claims"]
    counts = Counter(item["status"] for item in items)
    lines = [
        "# Claim Ledger",
        "",
        "> Generated from [`claim_ledger.json`](claim_ledger.json). Do not edit this file by hand.",
        "> Claim status is independent of review acceptance, freeze state, CI, and provenance completeness.",
        "",
        "## Status summary",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    for status in claims["status_vocabulary"]:
        lines.append(f"| {code(status)} | {counts.get(status, 0)} |")
    lines += [
        "",
        "## Claims",
        "",
        "| ID | Status | Track | Statement | Dependencies | Note |",
        "|---|---|---|---|---|---|",
    ]
    for item in items:
        dependencies = ", ".join(code(dep) for dep in item.get("depends_on", [])) or "—"
        lines.append(
            "| "
            + " | ".join(
                [
                    code(item["id"]),
                    code(item["status"]),
                    code(item["track"]),
                    cell(item["statement"]),
                    dependencies,
                    cell(item.get("note", "")),
                ]
            )
            + " |"
        )
    lines += [
        "",
        "The canonical vocabulary and promotion rules are defined in "
        "[`governance/CLAIM-STATUS.md`](../governance/CLAIM-STATUS.md) and "
        "[`governance/REVIEW-AND-FREEZE.md`](../governance/REVIEW-AND-FREEZE.md).",
        "",
    ]
    return "\n".join(lines)


def render_proof_graph(graph: dict[str, Any]) -> str:
    nodes = graph["nodes"]
    edges = graph["edges"]
    type_counts = Counter(node["type"] for node in nodes)
    status_counts = Counter(node["status"] for node in nodes)
    lines = [
        "# Proof Graph",
        "",
        "> Generated from [`proof_graph.json`](proof_graph.json). Do not edit this file by hand.",
        "> Graph structure is a research dependency model, not a mathematical review verdict.",
        "",
        "## Summary",
        "",
        f"- Nodes: **{len(nodes)}**",
        f"- Directed edges: **{len(edges)}**",
        f"- Open leaf nodes: **{sum(1 for node in nodes if node['type'] == 'leaf' and node['status'] == 'open')}**",
        "- Node types: " + ", ".join(f"{code(k)} {v}" for k, v in sorted(type_counts.items())),
        "- Node statuses: " + ", ".join(f"{code(k)} {v}" for k, v in sorted(status_counts.items())),
        "",
        "## Nodes",
        "",
        "| ID | Title | Type | Status | Artifact |",
        "|---|---|---|---|---|",
    ]
    for node in nodes:
        artifact = node.get("artifact")
        artifact_cell = relative_link("research/PROOF_GRAPH.md", f"research/{artifact}", artifact) if artifact else "—"
        lines.append(
            "| "
            + " | ".join(
                [
                    code(node["id"]),
                    cell(node["title"]),
                    code(node["type"]),
                    code(node["status"]),
                    artifact_cell,
                ]
            )
            + " |"
        )
    lines += [
        "",
        "## Edges",
        "",
        "| From | Relation | To |",
        "|---|---|---|",
    ]
    for edge in edges:
        lines.append(f"| {code(edge['from'])} | {code(edge['kind'])} | {code(edge['to'])} |")
    lines.append("")
    return "\n".join(lines)


def render_work_queue(queue: dict[str, Any]) -> str:
    lines = [
        "# Work Queue",
        "",
        "> Generated from [`work_queue.json`](work_queue.json). Do not edit this file by hand.",
        "> Issue and branch metadata coordinate work; the leaf packet, claim ledger, and proof graph carry scientific scope.",
        "",
        "| Priority | Leaf | Graph node | Issue | Claim dependencies | Track |",
        "|---|---|---|---|---|---|",
    ]
    for leaf in queue["leaves"]:
        leaf_link = relative_link("research/WORK_QUEUE.md", leaf["artifact"], leaf["title"])
        issue = f"[#{leaf['issue_number']}](https://github.com/snissn/planar-jacobian/issues/{leaf['issue_number']})"
        deps = ", ".join(code(dep) for dep in leaf["claim_dependencies"]) or "—"
        track = relative_link("research/WORK_QUEUE.md", leaf["track_artifact"], Path(leaf["track_artifact"]).name)
        lines.append(
            f"| {code(leaf['priority'])} | {leaf_link} | {code(leaf['graph_node'])} | {issue} | {deps} | {track} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_issue_index(queue: dict[str, Any]) -> str:
    lines = [
        "# GitHub Issue Index",
        "",
        "> Generated from [`work_queue.json`](work_queue.json). Do not edit this file by hand.",
        "",
        "The leaf packets are the durable scientific specification. GitHub issues are coordination mirrors and do not override the claim ledger or proof graph.",
        "",
        "| Leaf | Graph node | Issue |",
        "|---|---|---|",
    ]
    for leaf in sorted(queue["leaves"], key=lambda item: item["id"]):
        artifact = relative_link("research/ISSUE_INDEX.md", leaf["artifact"], Path(leaf["artifact"]).name)
        issue = f"[#{leaf['issue_number']}](https://github.com/snissn/planar-jacobian/issues/{leaf['issue_number']})"
        lines.append(f"| {artifact} | {code(leaf['graph_node'])} | {issue} |")
    lines.append("")
    return "\n".join(lines)


def render_legacy_migration(legacy: dict[str, Any]) -> str:
    lines = [
        "# Legacy Claim-Ledger Migration",
        "",
        "> Generated from [`legacy_claim_ledger.json`](legacy_claim_ledger.json). Do not edit this file by hand.",
        "> This is a historical reconciliation record, not a second authoritative claim ledger.",
        "",
        f"Source: {code(legacy['source_ref'])}, path {code(legacy['source_path'])}.",
        "",
        "## Status migration",
        "",
        "| Legacy status | Canonical treatment | Migration rule |",
        "|---|---|---|",
    ]
    for row in legacy["status_migration"]:
        lines.append(
            f"| {code(row['legacy_status'])} | {cell(row['canonical_treatment'])} | {cell(row['rule'])} |"
        )
    lines += [
        "",
        "## Preserved legacy claims",
        "",
        "| Legacy ID | Legacy status | Statement | Canonical links | Original note |",
        "|---|---|---|---|---|",
    ]
    for item in legacy["claims"]:
        links = ", ".join(
            f"{code(link['claim_id'])} ({cell(link['relation'])})" for link in item.get("canonical_links", [])
        ) or "unmapped; retained here only"
        lines.append(
            "| "
            + " | ".join(
                [
                    code(item["id"]),
                    code(item["legacy_status"]),
                    cell(item["statement"]),
                    links,
                    cell(item.get("notes", "")),
                ]
            )
            + " |"
        )
    lines += [
        "",
        "No migration row promotes a scientific claim. Canonical claim statements and statuses remain those in "
        "[`claim_ledger.json`](claim_ledger.json).",
        "",
    ]
    return "\n".join(lines)


def render_status(
    claims: dict[str, Any], graph: dict[str, Any], queue: dict[str, Any], manifest: dict[str, Any]
) -> str:
    claim_counts = Counter(item["status"] for item in claims["claims"])
    node_counts = Counter(item["status"] for item in graph["nodes"])
    open_leaves = [item for item in queue["leaves"] if item["status"] == "open"]
    metadata_exports = [item for item in manifest["exports"] if item.get("storage_mode") == "metadata_only"]
    p0 = [item for item in open_leaves if item["priority"] == "P0"]
    lines = [
        "# Repository Status",
        "",
        "> Generated from the maintained JSON ledgers by [`scripts/render_views.py`](scripts/render_views.py).",
        "",
        "## Authority and scientific boundary",
        "",
        "- **Repository authority:** `MUTABLE_NONAUTHORITATIVE` research baseline unless a file identifies a narrower reviewed or frozen scope.",
        "- **Main theorem:** open in this repository; `ROOT-JC2` remains `blocked`.",
        "- **Structural validation:** engineering evidence only; it is not mathematical review.",
        "- **Claim promotion in this reconciliation:** none.",
        "",
        "## Machine-derived inventory",
        "",
        f"- Claims: **{len(claims['claims'])}** across **{len(claim_counts)}** statuses.",
        f"- Proof graph: **{len(graph['nodes'])}** nodes and **{len(graph['edges'])}** directed edges.",
        f"- Graph node statuses: " + ", ".join(f"{code(k)} {v}" for k, v in sorted(node_counts.items())) + ".",
        f"- Open canonical leaf packets: **{len(open_leaves)}**.",
        f"- Metadata-only conversation exports: **{len(metadata_exports)}**; completion remains issue [#22](https://github.com/snissn/planar-jacobian/issues/22).",
        "",
        "## Review and coordination state",
        "",
        "Current-main review artifacts record an independent `ACCEPT` for the defect-four candidate at "
        "`96fc7ec34bd3b685a0edeae7ecd4404abab7e2f1`. The accompanying claim/graph delta is explicitly proposal-only and was not applied during this structural reconciliation. Issue [#17](https://github.com/snissn/planar-jacobian/issues/17) therefore remains a coordination surface until maintainers apply any reviewed scientific delta under the repository workflow.",
        "",
        "Issue [#2](https://github.com/snissn/planar-jacobian/issues/2), the machine-readable queue, and the canonical leaf packets are the active program navigation surfaces. Closed issue #1 and its branches are historical provenance only.",
        "",
        "## P0 queue",
        "",
    ]
    for leaf in p0:
        rel = os.path.relpath(ROOT / leaf["artifact"], start=ROOT).replace(os.sep, "/")
        lines.append(
            f"- {code(leaf['id'])}: [{leaf['title']}]({rel}) — issue [#{leaf['issue_number']}](https://github.com/snissn/planar-jacobian/issues/{leaf['issue_number']})."
        )
    lines += [
        "",
        "Run `python3 scripts/frontier.py` for the complete generated frontier and status counts.",
        "",
        "## Provenance warning",
        "",
        "The conversation summaries and declared hashes are retained as provenance and idea input. The unavailable complete exports were not reconstructed or fabricated; their storage mode remains `metadata_only`.",
        "",
    ]
    return "\n".join(lines)


def expected_outputs() -> dict[str, str]:
    claims = load_json("research/claim_ledger.json")
    graph = load_json("research/proof_graph.json")
    queue = load_json("research/work_queue.json")
    legacy = load_json("research/legacy_claim_ledger.json")
    manifest = load_json("archive/manifest.json")
    return {
        "research/CLAIM_LEDGER.md": render_claim_ledger(claims),
        "research/PROOF_GRAPH.md": render_proof_graph(graph),
        "research/WORK_QUEUE.md": render_work_queue(queue),
        "research/ISSUE_INDEX.md": render_issue_index(queue),
        "research/LEGACY_CLAIM_MIGRATION.md": render_legacy_migration(legacy),
        "STATUS.md": render_status(claims, graph, queue, manifest),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated Markdown views")
    mode.add_argument("--check", action="store_true", help="verify generated Markdown views are current")
    args = parser.parse_args()

    stale: list[str] = []
    for relative_path, expected in expected_outputs().items():
        path = ROOT / relative_path
        expected_bytes = (expected.rstrip() + "\n").encode("utf-8")
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected_bytes)
            print(f"wrote {relative_path}")
        else:
            actual = path.read_bytes() if path.exists() else b""
            if actual != expected_bytes:
                stale.append(relative_path)

    if stale:
        for path in stale:
            print(f"STALE: {path}")
        print("Run: python3 scripts/render_views.py --write")
        return 1
    if args.check:
        print(f"generated views: PASS ({len(expected_outputs())} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
